plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.lgy8687.timebook'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.lgy8687.timebook'
        minSdk 24
        targetSdk 34
        versionCode 2
        versionName '0.2-test'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
}
